### ISSUE TITLE
versioning reliability

### ISSUE THREAD

**Issue by mwallschlaeger** [GeoNodeUserGroup-DE/contrib_externalapplications#6]
as we are building from this repository, we require a stable versioning of this package. @ridoo can you confirm to keep tags like this, and v1.0.0 is made to work for geonode 4.2.x?

**Comment by ridoo** [comment]
Yes. `v1.0.1` is the latest version supporting geonode `v4.2.x`. I created branches for both GeoNode `v4.2.x` and `v4.3.x` (there were breaking changes). A stable version for GeoNode `v4.3.0` has been tagged as `2.0.0`.
