### ISSUE TITLE
Add funding information

### ISSUE THREAD

**Issue by gannebamm** [GeoNodeUserGroup-DE/contrib_externalapplications#7]
Since ZALF funded the latest maintenance (4.2.x to 4.3.x) I would vote for adding it in the funders list (https://github.com/GeoNodeUserGroup-DE/contrib_externalapplications#funding)

It think this is a good workflow for all our UserGroup outputs. @specka @mwallschlaeger oppinions?

**Comment by specka** [comment]
I think, this would be great. I cannot think why this could be negative for ZALF.

**Comment by ridoo** [comment]
No problem. I will take care on this .. did this already for the [importer-datapackage repo](https://github.com/GeoNodeUserGroup-DE/importer-datapackage/#funding).
